apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test
  namespace: web
  labels:
    app: web-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-test
  template:
    metadata:
      labels:
        app: web-test
    spec:
      containers:
      - name: web-test
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
          - name: NGINX_HOST
            value: "foobar.com"
          - name: NGINX_PORT
            value: "80"
