apiVersion: v1
kind: Service
metadata:
  name: web-test-service
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: web-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80